### ISSUE TITLE
Feature request: Exclude tautologies

### ISSUE THREAD

**Issue by matentzn** [phenoscape/owlery#10]
It would be great if I had a flag for the REST call to exclude owl:Nothing from the list of subclasses (not of course from the list of superclasses!) and owl:Thing from the list of superclasses (not from the list of subclasses).

**Comment by balhoff** [comment]
I added `includeNothing` (default `false`) to the subclasses call, and `includeThing` (default `false`) to the superclasses and types calls (on `master` now).

They could be the same if I called it `includeTautologies` instead, but I just wanted to be straightforward. And the default is to not include, so you can generally leave these parameters off.
