### ISSUE TITLE
Log4J configuration missing?

### ISSUE THREAD

**Issue by rpgoldman** [phenoscape/owlery#131]
Trying to start Owlery from the Docker container I get the following warning, because of a missing or incorrect `log4j` configuration.  I *did* read the FAQ the error cites but ... it is not at all helpful.  In particular, it says 

  > Knowing the appropriate location to place log4j.properties or log4j.xml requires understanding the search strategy of the class loader in use. 

A little googling suggests that I might need to put something in the `akka` configuration, but I am not sure what.  But I'm not sure that is right, since the error message just mentions jena.

```
docker run --rm -p 8080:8080 -v /Users/rpg/projects/xplan/container-ontology/owl/:/srv/owl -v /Users/rpg/projects/xplan/container-ontology/owl/owlery-conf:/srv/config phenoscape/owlery:latest
log4j:WARN No appenders could be found for logger (org.apache.jena.util.FileManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Comment by rpgoldman** [comment]
@balhoff I just looked at `/usr/share/owlery/bin/owlery`, and it looks like there *is* a log4j implementation included in Owlery's classpath:  `$lib_dir/log4j.log4j-1.2.17.jar`.

And I checked and the jar file is there in the Docker image.

Trying to follow the suggestion [here](https://github.com/owlcs/owlapi/issues/1015), I ran the docker image as follows, but adding the default log level flag has had no visible effect:

    docker run --rm --env JAVA_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG -p 8080:8080 -v /Users/rpg/projects/xplan/container-ontology/owl//server-files:/srv/owl -v /Users/rpg/projects/xplan/container-ontology/owl/owlery-conf:/srv/conf owlery:latest

When I run a bash shell inside the container I see that `JAVA_OPTS` is bound, so I *assume* that Java is seeing it, it's just not having an effect, possibly because of the log4j configuration issue. Will experiment more.

**Comment by rpgoldman** [comment]
I should correct the above: it *does* seem to work to the extent that this removes the log4j warning method. But ... I am still not seeing any log entries out of OWLAPI.  So perhaps I need to be doing something to redirect the logging for OWLAPI to a different location.

I wish the Java logging infrastructure wasn't so complicated...

**Comment by rpgoldman** [comment]
I'm closing this because I read the logs, found a couple of IRI issues, fixed them, and everything is working brilliantly!  Thanks to both of you, @balhoff and @hlapp

**Comment by balhoff** [comment]
That's great, thanks for your perseverance. A lot of things are in better shape as a result.

**Comment by rpgoldman** [comment]
The thanks are all due to you, for fixing things so quickly!
