### ISSUE TITLE
Queries unexpectedly find no answers

### ISSUE THREAD

**Issue by rpgoldman** [phenoscape/owlery#133]
# Summary

I managed to get the Owlery server up and, *as far as I can tell* it has loaded my ontology files successfully.  However, when I do obvious queries -- what are all of the Individuals of type `owl:Thing`? what are all the subclasses of `owl:Thing`? with `direct=false` -- I get only empty lists.

# Loading Successfully

Why do I say "_as far as I can tell_ it has loaded my ontology files successfully"?

Before, Owlery was trying to read my Mac's `.DS_Store` file as an ontology and erroring out . It no longer does that -- it just says it has started. So I *assume* that my ontology files were loaded successfully, but I don't see that there's any way to tell.  Maybe the logging could be enhanced to give more feedback about loading?  This would probably be particularly helpful when working with OWLAPI, because it treats as warnings or info things which seem very bad to me.

Even with the Akka log-level set to `DEBUG` all I see is 

```
[DEBUG] [08/18/2021 15:52:29.396] [main] [EventStream(akka://Main)] logger log1-Logging$DefaultLogger started
[DEBUG] [08/18/2021 15:52:29.398] [main] [EventStream(akka://Main)] Default Loggers started
[DEBUG] [08/18/2021 15:52:29.466] [main] [akka.serialization.Serialization(akka://Main)] Replacing JavaSerializer with DisabledJavaSerializer, due to `akka.actor.allow-java-serialization = off`.
[DEBUG] [08/18/2021 15:52:29.583] [main] [AkkaSSLConfig(akka://Main)] Initializing AkkaSSLConfig extension...
[DEBUG] [08/18/2021 15:52:29.585] [main] [AkkaSSLConfig(akka://Main)] buildHostnameVerifier: created hostname verifier: com.typesafe.sslconfig.ssl.NoopHostnameVerifier@448b808a
[DEBUG] [08/18/2021 15:52:30.015] [Main-akka.actor.internal-dispatcher-2] [akka://Main/system/IO-TCP/selectors/$a/0] Successfully bound to /0.0.0.0:8080
[INFO] [08/18/2021 15:52:30.041] [Main-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(Main)] Server online at http://0.0.0.0:8080/
Press RETURN to stop...
```

I don't know if there is some other logging configuration available that I should be using.  As I said, though, I did get an error message and backtrace when Owlery tried to parse a file that was not an ontology.

# Queries that give empty results:

1. No subclasses of `owl:Thing`:

```
$ curl --location --request GET 'http://localhost:8080/kbs/strateos-catalog/subclasses?kb=strateos-catalog&object=owl%3AThing&prefixes=%7B%20%22owl%22%20%3A%20%20%22http%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%2523%22%7D&direct=false'
{"@id":"http://www.w3.org/2002/07/owl%23Thing","superClassOf":[],"@context":"https://owlery.phenoscape.org/json/context.jsonld"}
```

2. No Individuals of type `owl:Thing`:
```
$ curl --location --request GET 'http://localhost:8080/kbs/strateos-catalog/instances?kb=strateos-catalog&object=owl%3AThing&prefixes=%7B%20%22owl%22%20%3A%20%20%22http%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%2523%22%7D&direct=false'
{"@id":"http://www.w3.org/2002/07/owl%23Thing","hasInstance":[],"@context":"https://owlery.phenoscape.org/json/context.jsonld"}
```

# Replication

If one wanted to replicate, one could check out [my repo for the container ontology](https://github.com/rpgoldman/container-ontology/), `cd` to the `owl` subdirectory and do `make server`.  Then try the queries above.

# Aside about request formatting

I wasn't entirely sure what a JSON-formatted prefix map would be, especially when used as a parameter instead of putting it in the JSON body of a `POST` request.

I looked at [this document](https://www.w3.org/2011/rdf-wg/wiki/JSON_Syntax_Options) but it was of limited assistance.

What I guessed would be right was to have an object with the abbreviations as keys and the URL as values. I *think* I did that correctly because of the response (but perhaps the `owl` prefix is built in?), and because in other cases I got errors when I gave an ill-formed query.

# Aside about configuration file

Maybe it should be possible to supply a glob pattern instead of just a directory name in the configuration file? something like `/srv/owl/*.ttl` instead of just `/srv/owl`.  That would avoid the contortions I have to go through to keep Owlery from seeing crud like `.DS_Store`.

**Comment by rpgoldman** [comment]
Update: I have tried with Owlery configured to use the structural reasoner and HermiT and I get the same results both times.

**Comment by balhoff** [comment]
@rpgoldman could you commit `application.conf` to your example repo? I'm trying to run `make server` and getting `com.typesafe.config.ConfigException$IO: /srv/conf/application.conf: java.io.FileNotFoundException: /srv/conf/application.conf (No such file or directory)`

**Comment by balhoff** [comment]
I think the issue may be that your owl prefix is double-encoded. When I URL-decode your JSON object (looks like you had the right idea for the structure), I get this:

```
{ "owl" :  "http://www.w3.org/2002/07/owl%23"}
```

But is should be:

```
{ "owl" :  "http://www.w3.org/2002/07/owl#"}
```

**Comment by balhoff** [comment]
By the way, if your files were loaded correctly, you should see some statistics returned at `http://localhost:8080/kbs/strateos-catalog`

**Comment by rpgoldman** [comment]
> @rpgoldman could you commit `application.conf` to your example repo? I'm trying to run `make server` and getting `com.typesafe.config.ConfigException$IO: /srv/conf/application.conf: java.io.FileNotFoundException: /srv/conf/application.conf (No such file or directory)`

Hi, @balhoff -- sorry about that.  The `application.conf` file is in the `owlery-server` branch of my git repo: https://github.com/rpgoldman/container-ontology/tree/owlery-server

**Comment by rpgoldman** [comment]
> By the way, if your files were loaded correctly, you should see some statistics returned at `http://localhost:8080/kbs/strateos-catalog`

Looks like maybe my ontology is being read correctly, but the imports maybe not?

<img width="730" alt="image" src="https://user-images.githubusercontent.com/3274/130127123-bf81511e-9b50-48f5-a21e-12eb60720fc7.png">

Actually, it's hard to tell, because the import files are all contained in the directory that I pass to Owlery, so maybe they don't count as imports?

**Comment by balhoff** [comment]
It's possible the imports are causing some problems. I see that your files import each other. The best way to make that work would be to provide a catalog file to map the IRIs to the local files, but there is a longstanding issue about that: #17 (it has just never really been needed by current users).

A straightforward workaround is to merge the files ahead of time using ROBOT, which does support a catalog file already. Or, for your case you can just delete your import statements, since all the files in the input directory are merged into one in-memory ontology in Owlery.

I may tackle #17 in the near term, since I am hoping to address the various issues you're encountering as a new user.

**Comment by rpgoldman** [comment]
> I think the issue may be that your owl prefix is double-encoded. When I URL-decode your JSON object (looks like you had the right idea for the structure), I get this:
> 
> ```
> { "owl" :  "http://www.w3.org/2002/07/owl%23"}
> ```
> 
> But is should be:
> 
> ```
> { "owl" :  "http://www.w3.org/2002/07/owl#"}
> ```

Yes!  That seems to have fixed my problem!

**Comment by balhoff** [comment]
Great! Also, it may not be obvious what the syntax is for more complex queries. It uses Manchester syntax, where the value for `object` would be a URL-encoded string like this (note you can use full IRIs inside angle brackets):

```
<http://sbols.org/v3#hasModel> some owl:Thing
```

**Comment by rpgoldman** [comment]
I'm going to close this, because DL queries seem to be working successfully for me now.  Thanks for the help!
