### ISSUE TITLE
DL Queries not getting expected answers: parsing issues

### ISSUE THREAD

**Issue by rpgoldman** [phenoscape/owlery#142]
Using the `make server` command to set up Owlery as per [this makefile](https://github.com/rpgoldman/container-ontology/blob/owlery-server/owl/Makefile) I am getting query failures I did not expect. 

Here's the `curl` query I use:

```
curl -G --location --request GET 'http://localhost:8080/kbs/strateos-catalog/instances' --data "kb=strateos-catalog" --data-urlencode "object=cont:Plate and (cont:wellCount value 96)"   --data 'direct=false' --data-urlencode 'prefixes={ "owl" :  "http://www.w3.org/2002/07/owl#", "cont": "https://raw.githubusercontent.com/rpgoldman/container-ontology/owlery-server/owl/container-ontology.ttl#"}'
```

The important bit is `object=cont:Plate and (cont:wellCount value 96)` and the error I get back is:

```
requirement failed: Encountered 96 at line 1 column 38. Expected one of:
	Individual name
```

It looks like Owlery believes that my `cont:wellCount` property is an object property, even though it is defined as a data property, that is positive integer valued.

When I do what I *think* is the corresponding query in Protege, `cont:Plate and cont:wellCount value 96` I get 22 results.

P.S. You might consider activating the "Discussions" GitHub action in addition to issues, if it bothers you that I am abusing Issues to ask questions.

## Note on replication

Note that this is replicable as follows:

1. `git clone https://github.com/rpgoldman/container-ontology`
2. `git checkout owlery-server`
3. `cd owl`
4. `make server`
5. Execute queries

## Possible explanation: Bad syntax

It's quite possible that I'm doing something wrong in authoring my Manchester Syntax query expressions.  But reading the [OWL 2 Web Ontology Language Manchester Syntax (Second Edition)](https://www.w3.org/TR/owl2-manchester-syntax/#IRIs.2C_Integers.2C_Literals.2C_and_Entities) it didn't look like I needed any special syntax for an integer literal.

## Possible explanation: Some problem with properties

I wondered whether Owlery somehow isn't getting my property definitions, and so it might be assuming that `cont:wellCount` is an object property instead of a datatype property?  I tried asking Owlery to find all of my DatatypeProperty's, ObjectProperty's and AnnotationProperty's but was not successful. I don't know if such a query is possible in Owlery.

I tried using the `sparql` endpoint, but could not get that to work at all: all of my queries returned an empty set of results.

## Possible explanation: Import problem

One possible explanation is that there has been an import problem.  When I query Owlery for my ontology (`strateos-catalog`) I see this:
```
{
    "label": "strateos-catalog",
    "logicalAxiomsCount": 1318,
    "@context": "https://owlery.phenoscape.org/json/context.jsonld",
    "isConsistent": true,
    "imports": [],
    "@id": "_:anonymousOnt0"
}
```
If I look at Protege for the same ontology, I see this:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/3274/130868738-cd8409d2-a6d3-44f4-ad29-34f658d0bd9d.png">

### Another possible clue

Owlery is reporting that it has 1318 logical axioms.  Looking at the Protege display for `strateos-catalog`, I see 1303.  The included container-ontology, Protege displays as having 415, and the om-subset ontology (also imported) has 15. **If** the definition of logical axioms is the same between Owlery and Protege, then Owlery believes there are 1318 logical axioms and Protege believes there are 1733.  I don't know if the definitions are different, or Owlery is not seeing some of my axioms.  Actually, if the two definitions *are* the same, this would be consistent with Owlery reading only my strateos-catalog.ttl and the om-subset.ttl, and missing the container-ontology.ttl entirely.

I'm afraid I'm not sure how to debug this, if it is an import issue, since I am not getting any log data (see #131).  Is there anything I can do to configure log4j so that it writes to the console or a file?  Sorry to be so clueless, but log4j is a really big thing and I don't know where to start, especially since their own docs say that there is no way for a user to tell where the log4j config files should go.

That said, it looks like at least one of the imported ontologies is, in fact, imported, since when I ask Owlery for all the instances of `cont:Plate` (lab multi-well plates), I get a set that contains not just the entities from my main ontology (`strateos-catalog.ttl`), but also the foundational ontology it imports (`container-ontology.ttl`).

So this may be a red herring, since Owlery is loading all the files in the directory, it may be that it does not see `container-ontology.ttl` as an import -- it's loaded manually.

OTOH, OWLAPI does not feel that it's an error when it can't process a triple and throws it on the floor. These are logged, but only as WARN or INFO, I believe and (broken record) I can't see the logs.

**Comment by rpgoldman** [comment]
I think there must be some loading issue or something.  I have found under some circumstances that OWLAPI will ignore my catalog file and pull the URL instead, and it isn't guaranteed that the ontologies at the URL references are up-to-date wrt my local copies.

I just reloaded, and according to Protege, there are 1313 logical axioms:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/3274/131197373-e6ec7122-9a74-491d-92f4-1e0f2c1d6a5f.png">
I don't know what it means that there's an `Axiom` line with 2036.  Does that mean there are 2026-1313 = 713 *illogical* axioms?

The Swagger API to Owlery reports the following:
```
{
  "label": "strateos-catalog",
  "logicalAxiomsCount": 1552,
  "@context": "https://owlery.phenoscape.org/json/context.jsonld",
  "isConsistent": true,
  "imports": [],
  "@id": "_:anonymousOnt0"
}
```

**Comment by balhoff** [comment]
@rpgoldman in case you didn't see—I added some docs on using a catalog file to the [README](https://github.com/phenoscape/owlery#locating-ontologies-via-iri).

**Comment by rpgoldman** [comment]
@balhoff I *did* see that, thanks, and I have tried replacing the location with the main file, and adding the IRIs for the main file, and all its imported ontologies to the catalog:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    <uri name="https://raw.githubusercontent.com/rpgoldman/container-ontology/main/owl/om-subset.ttl" uri="/srv/owl/om-subset.ttl"/>
    <uri name="https://raw.githubusercontent.com/rpgoldman/container-ontology/main/owl/container-ontology.ttl" uri="/srv/owl/container-ontology.ttl"/>
    <uri name="https://raw.githubusercontent.com/rpgoldman/container-ontology/main/owl/strateos-catalog-individuals.ttl" uri="/srv/owl/strateos-catalog-individuala.ttl"/>
    <group id="Folder Repository, directory=, recursive=true, Auto-Update=true, version=2" prefer="public" xml:base=""/>
</catalog>
```

And... I can see I made a typo in the catalog entry above for strateos-catalog-individuals.ttl .  What's pretty worrying is that I got no error message at all for this, and Owlery seems to have gone ahead and loaded.... what? Presumably the copy at `raw.githubusercontent.com`?

I feel like a broken record, and I'm sorry about that, but some logging here would be a *huge* help in debugging.

**Comment by rpgoldman** [comment]
Even after that, I am still getting 

```
requirement failed: Encountered 96 at line 1 column 37. Expected one of:
	Individual name
```

It occurs to me to wonder: is there any way to make a query to Owlery to see what it believes about a `Property`? Or is that only available for individuals and classes?

**Comment by balhoff** [comment]
> It occurs to me to wonder: is there any way to make a query to Owlery to see what it believes about a `Property`? Or is that only available for individuals and classes?

There aren't any endpoints for this now, but I think it could be added.
