### ISSUE TITLE
OWLERY changes IRIs of individuals (Bug)

### ISSUE THREAD

**Issue by matentzn** [phenoscape/owlery#16]
If you check for instances (I did not observe this for subclasses, but it may be accidental), the return set includes changed IRIs. Compare the [ABEROWL](http://owl.virtualflybrain.org/api/runQuery.groovy?type=realize&query=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00005106%3E+and+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002131%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00007054%3E&ontology=VFB) call to the [OWLERY](http://owl.virtualflybrain.org/kbs/vfb/instances?object=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00005106%3E+and+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002131%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00007054%3E&direct=false) call. 

Note that owlery returns individuals with an IRI such as 
http://www.virtualflybrain.org/owl/VFB_00007104
while the true IRI is 
http://virtualflybrain.org/owl/VFB_00007104

As this is quite urgent for us: Is there anything I can do to help fix this? Thank you very much!

**Comment by balhoff** [comment]
@matentzn how are you specifying the OWL file(s) to load at startup? Is it one file, or a URI, or a folder of files? There is very little code between the REST endpoint and calling the OWL API reasoner, so I'm wondering if there is a problem when loading the ontology.

**Comment by matentzn** [comment]
@Robbie1977 do you have an idea?

**Comment by matentzn** [comment]
Jim, it is possible! I remember there was a discussion about changing IRIs across ontologies, and it is possible the service was not restarted after that. Lets see what Robbie will say.

**Comment by matentzn** [comment]
Okay, we were using an older version of our KB. Sorry for the mix-up.
