### ISSUE TITLE
Dockerhub Owlery image out of date?

### ISSUE THREAD

**Issue by rpgoldman** [phenoscape/owlery#166]
I built my own, which I have been using, but I noticed that the one on DockerHub seems to be out of date.  The Dockerhub entry shows the image as being 8 months old, and I think there are some big fixes since then.

**Comment by hlapp** [comment]
Yes, DockerHub stopped auto-builds for non-premium users a few months ago. So one would need to build and then push the images by hand. The best path forward is probably to delete the DockerHub images altogether, and instead use GitHub packages as the image repo, and GitHub actions for auto-building and updating the images.

**Comment by rpgoldman** [comment]
@hlapp Wouldn't an interim approach be to auto-build with the GitHub actions and push to DockerHub from there?  This would require figuring out how to use secrets in GitHub actions, but might be an easy first step.

I'm slowly fighting my way through trying to understand GitHub Actions...

**Comment by hlapp** [comment]
Using the GitHub package repo is actually the easy part. So, no, I don't think what you suggest would be a good interim approach, because figuring out the migration to Github Actions is 95% of the difficulty, so you might as well go all the way.

**Comment by rpgoldman** [comment]
But maybe hand-push an up-to-date image now? I built my own (it's available as `rpgoldman/owlery:latest`), but it seems wrong to leave around an official one that is out-of-date.

**Comment by Robbie1977** [comment]
@hlapp I've added a PR (#184) to help with your dockerhub issues
